---
title: "Thesis Data Analysis - Data Cleaning"
author: "Sofia Lai"
date: "3/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries
```{r}
pacman::p_load(haven, tidyverse, ggplot2, table1, readxl, gtsummary, writexl, stargazer, questionr, flextable, magrittr)
```

Reading and tidying data 
```{r}
dat1 <- read_excel("responses-eng.xlsx")

dat1 <- dat1 %>% 
  rename("empl" = "Are you currently employed or have been employed during the last 12 months?", 
         "ger" = "Are you currently living in Germany?", 
         "income" = "What is your current gross annual income (EUR)?", 
         "gender" = "What is your gender?",
         "age" = "How old are you?",
         "hours" = "How many weekly hours are you currently working?", 
         "job_boring" = "I consider my job boring",
         "job_interesting" = "I consider my job interesting", 
         "job_repetitive" = "My job consists of repetitive tasks", 
         "job_stimulating" = "I perceive my job as stimulating", 
         "job_social_status" = "My job gives me social status", 
         "job_ashamed" = "I am ashamed of my job", 
         "job_satisfied" = "I am satisfied with my job", 
         "job_unsatisfied" = "I am not satisfied with my job", 
         "ubi_300" = "Universal basic income (UBI) is defined as a monthly transfer of money, independent of any requirements. What would you do with a UBI of EUR 300?", 
         "what_income_300" = "How would you use your additional income?...16", 
         "what_less_300" = "Ideally, around what percentage would you like to reduce your weekly working hours?...17", 
         "what_time_300" = "What would you do with the extra free time?", 
         "change_500" = "Consider now a monthly UBI of EUR 500. Would your previous answers change?", 
         "ubi_500" = "What would you do with a monthly UBI of EUR 500?", 
         "what_less_500" = "Ideally, around what percentage would you like to reduce your weekly working hours?...21", 
         "what_time_500" = "What would you do with your additional free time?...22", 
         "what_income_500" = "What would you do with your additional income?", 
         "change_800" = "Finally, consider a monthly UBI of EUR 800. Would this change your previous answers?", 
         "ubi_800" = "What would you do with a monthly UBI of EUR 800?", 
         "what_income_800" = "How would you use your additional income?...26", 
         "what_less_800" = "Ideally, around what percentage would you like to reduce your weekly working hours?...27", 
         "what_time_800" = "What would you do with your additional free time?...28", 
         "time_change" = "Assume you start receiving UBI from tomorrow. Over what period of time do you expect your chances of finding employment to improve?", 
         "expect" = "Select which of the following applies to you.")  %>% 
  replace_na(list("job_boring" = 0, 
                  "job_interesting" = 0, 
                  "job_repetitive" = 0, 
                  "job_stimulating" = 0, 
                  "job_social_status" = 0, 
                  "job_ashamed" = 0, 
                  "job_satisfied" = 0, 
                  "job_unsatisfied" = 0)) %>% 
  mutate("job_boring" = factor(ifelse(job_boring == 0, 0, 1)),
         "job_interesting" = factor(ifelse(job_interesting == 0, 0, 1)),
         "job_repetitive" = factor(ifelse(job_repetitive == 0, 0, 1)),
         "job_stimulating" = factor(ifelse(job_stimulating == 0, 0, 1)),
         "job_social_status" = factor(ifelse(job_social_status == 0, 0, 1)),
         "job_ashamed" = factor(ifelse(job_ashamed == 0, 0, 1)),
         "job_satisfied" = factor(ifelse(job_satisfied == 0, 0, 1)),
         "job_unsatisfied" = factor(ifelse(job_unsatisfied == 0, 0, 1)),
         hours = sub("Less than 10", "0-10", hours))


dat_1 <- dat1 %>% 
  mutate(expect = case_when(
    expect == "I am currently employed part-time and UBI would increase my chances of finding full-time employment." ~ "Employed part-time, more chances of full-time employment with UBI", 
    expect == "None of the above" ~ "No change with UBI", 
    expect == "I am currently unemployed and UBI would increase my chances of finding part-time employment." ~ "Unemployed, more chances of part-time employment with UBI", 
    expect == "I am currently unemployed and UBI would increase my chances of finding full-time employment." ~ "Unemployed, more chances of full-time employment with UBI"
  )) %>% 
  replace_na(list("expect" = "No change with UBI."))

#Removing invalid responses
dat_1 <- dat_1 %>% 
  filter(empl == 1)

#When change_500 = 0 => ubi_500 = NA, it means that the response would not change from the previous one, hence: when change_NA = 0 => ubi_500 = ubi_300 
#when change_800 = 0 => ubi_800 = NA => ubi_800 = ubi_500 

dat2 <- dat_1 #duplicate data
dat2$ubi_500[is.na(dat2$ubi_500)] <- dat2$ubi_300[is.na(dat2$ubi_500)] #replace missing values of ubi_500 with values from ubi_300

dat3 <- dat2 #duplicate data
dat3$ubi_800[is.na(dat3$ubi_800)] <- dat3$ubi_500[is.na(dat3$ubi_800)] #replace missing values of ubi_800 with values from ubi_500


#Ensuring response "Stop working" is included even if N=0 
dat3$ubi_300 <- fct_expand(dat3$ubi_300, "Stop working")
dat3$ubi_300 <- relevel(dat3$ubi_300, ref = "Work the same amount as now")
dat3$ubi_500 <- fct_expand(dat3$ubi_500, "Stop working")
dat3$ubi_500 <- relevel(dat3$ubi_500, ref = "Work the same amount as now")
dat3$ubi_800 <- fct_expand(dat3$ubi_800, "Stop working")
dat3$ubi_800 <- relevel(dat3$ubi_800, ref = "Work the same amount as now")

#arrange columns alphabetically 
dat3 <- dat3 %>% select(order(colnames(dat3)))

##remove spaces between - in levels
dat4 <- dat3 %>% 
  mutate(age = gsub(" ", "", age), 
         income = gsub(" ", "", income),
         hours = gsub(" ", "", hours))

#merge eng and ger data
dat <- rbind(dat_de_6, dat4)

#formatting income levels, fixing typos
dat<- dat %>% 
  mutate(
    income = gsub("0-15.000", "0-15,000", income),
    income = gsub("15.000-30.000", "15,000-30,000", income),
    income = gsub("30.000-45.000", "30,000-45,000", income),
    income = gsub("45.000-60.000" ,  "45,000-60,000", income),
    income = gsub("60.000", "60,000", income))


dat <- dat %>% 
  mutate(
    what_income_300 = gsub("Spend it in material goods", "Spend it for material goods", what_income_300),
    what_income_500 = gsub("Spent it in material goods", "Spend it for material goods", what_income_500),
    what_income_500 = gsub("Spend it in material goods", "Spend it for material goods", what_income_500), 
    what_income_800 = gsub("Spent it in material goods", "Spend it for material goods", what_income_800), 
    what_income_800 = gsub("Spend it in material goods", "Spend it for material goods", what_income_800),
    what_income_800 = gsub("Spent it for material goods", "Spend it for material goods", what_income_800), 
    what_income_300 = gsub("Spend it for career training", "Spend it for career development training", what_income_300), 
    what_income_500 = gsub("Spend it for career training", "Spend it for career development training", what_income_500),
    what_income_800 = gsub("Spend it for career training", "Spend it for career development training", what_income_800))

#all variables as factors
dat$income <- as.factor(dat$income)
dat$age <- as.factor(dat$age)
dat$gender <- as.factor(dat$gender)
dat$hours <- as.factor(dat$hours)
dat$ubi_300 <- as.factor(dat$ubi_300)
dat$ubi_500 <- as.factor(dat$ubi_500)
dat$ubi_800 <- as.factor(dat$ubi_800)
dat$what_income_300 <- as.factor(dat$what_income_300)
dat$what_income_500 <- as.factor(dat$what_income_500)
dat$what_income_800 <- as.factor(dat$what_income_800)

dat <- dat %>% replace_na(list(c("what_less_300" = "No reduction"),
                  ("what_less_500" = "No reduction"),
                  ("what_less_800" = "No reduction")))

```

```{R}
# try scale for job satis 
# job_good : job_interesting, job_satisfied, job_social_status, job_stimulating (when sum > 2)
# job_bad : job_boring, job_ashamed, job_repetitive, job_unsatisfied 
dat <- dat %>% mutate(job_interesting = as.numeric(job_interesting), 
                       job_satisfied = as.numeric(job_satisfied),  
                       job_social_status = as.numeric(job_social_status), 
                       job_stimulating = as.numeric(job_stimulating), 
                       job_boring = as.numeric(job_boring), 
                       job_ashamed = as.numeric(job_ashamed), 
                       job_repetitive = as.numeric(job_repetitive), 
                       job_unsatisfied = as.numeric(job_unsatisfied)) 
#1 = 0, 2 = 1 
dat <- dat %>% 
  mutate(job_interesting = case_when(
      job_interesting == 1 ~ 0, 
      job_interesting == 2 ~ 1), 
    job_satisfied = case_when(
      job_satisfied == 1 ~ 0,
      job_satisfied == 2 ~ 1),
    job_social_status = case_when(
      job_social_status == 1 ~ 0,
      job_social_status == 2 ~ 1),
    job_stimulating = case_when(
      job_stimulating == 1 ~ 0, 
      job_stimulating == 2 ~ 1),
    job_boring = case_when(
      job_boring == 1 ~ 0,
      job_boring == 2 ~ 1), 
    job_ashamed = case_when(
      job_ashamed == 1 ~ 0,
      job_ashamed == 2 ~ 1), 
    job_repetitive = case_when(
      job_repetitive == 1 ~ 0,
      job_repetitive == 2 ~ 1), 
    job_unsatisfied = case_when(
      job_unsatisfied == 1 ~ 0,
      job_unsatisfied == 2 ~ 1)) 

#0 = min satisfaction/unsatisfaction, 4 = max satisfaction/unsatisfaction i
dat <- dat %>% 
  mutate(job_good =
    (job_interesting + job_satisfied + job_social_status + job_stimulating), 
    job_bad = (job_boring + job_ashamed + job_repetitive + job_unsatisfied))
                       

```

